version: '3.7'
services:
  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
      - '3000:3000'

    environment:
      - JWT_SECRET=batman
